version: '2'
services:
  lint-test:
    build:
      context: .
      dockerfile: Dockerfile-lint-test
    command:
      - bash
      - '-c'
      - 'rustfmt src/**.rs --check && cargo +nightly clippy && cargo test'
