FROM guangie88/rs-cider:1.29.0-nightly

WORKDIR /app
COPY ./Cargo.toml ./Cargo.lock ./rustfmt.toml ./

RUN set -x \
    && cargo fetch --locked -v

COPY ./src/ ./src/

RUN cargo +nightly clippy \
    && cargo test --no-run
